global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 30s

rule_files:
  - alert.rules.yml

scrape_configs:
  - job_name: simulator
    metrics_path: /health/metrics
    static_configs:
      - targets:
          - simulator:3001

  - job_name: mock_csms
    honor_labels: true
    metrics_path: /health/metrics
    static_configs:
      - targets:
          - mock-csms:9220
        labels:
          service: mock-csms

  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090
